version: '3'
services:
    mongodb:
      image: mongo
      command: mongod --setParameter localLogicalSessionTimeoutMinutes=90
      ports:
        - "27017:27017"

    mongo-seed:
      image: personalizedoncology/clinvap_reporting_db
      links:
       - mongodb

    api:
      image: personalizedoncology/clinvap_reporting_db_api
      ports:
        - "5000:5000"
      depends_on:
        - mongo-seed

    filedeploy:
      image: personalizedoncology/clinvap_file_deploy:v1.1_$ASSEMBLY
      volumes:
        - dependencyF:/mnt

    ClinicalReportR: 
      image: personalizedoncology/clinvap_reporting_app:v1.1
      volumes:
        - dependencyF:/data
        - ./ReportingApplication/inout:/inout
      network_mode: "host"
      depends_on:
        - api
        - mongo-seed
        - filedeploy
volumes:
  dependencyF: