version: '3'
services:
  db:
    image: mongo 
  example_data:
    build: .
    image: clinvap/report_db_api_example_data
    depends_on:
      - 'db'
    links:
      - 'db'
  api:
    image: clinvap/report_db_api
    build: ..
    depends_on:
      - 'example_data'
    links: 
      - 'db'
    environment:
      MONGO_HOST: db
    ports:
      - '5151:5151'